import { useRouter } from "next/router";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Post() {
  const router = useRouter();
  const { id } = router.query;
  return (
    <>
      <Head>
        <title>Calo Tiket</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <Image
            className={styles.logo}
            src="/Logo_3.png"
            alt="Next.js Logo"
            width={150}
            height={150}
            priority
          />
          <div>
            <a
              href="https://www.linkedin.com/in/muh-nur-746571216/"
              target="_blank"
              rel="noopener noreferrer"
            >
              By <h3>Muhammad Nurharianto </h3>
            </a>
          </div>
        </div>
        <div className={styles.grid}>
          <div
            className={styles.card}
            rel="noopener noreferrer"
            potition="center"
          >
            <h1>Calo Tiket</h1>
          </div>
        </div>
        <br />
        <div className={styles.grud}>
          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h3>Tanggal Trending</h3>
            <p>4-7 Juni 2023</p>
          </a>
          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h3>Jumlah Tweet</h3>
            <p>1414</p>
          </a>
          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h3>Deskripsi</h3>
            <p>
              Pembukaan penjualan tiket bola timnas indonesia vs argentina
              terjadi tanggal 4-6 juni 2023 tetapi karena antusias masyarakat
              banyak orang yang tidak kebagian tiket, hal ini menyebabkan banyak
              orang beramsumsi terdapat beberapa calo yang memborong tiket
            </p>
          </a>
        </div>
        <br />
        <br />
        <div className={styles.card} target="_blank" rel="noopener noreferrer">
          <div
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h3>User Pertama yang membuat trending</h3>
          </div>
          <div className={styles.grid}>
            <a
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h3>Username</h3>
              <p>Partai Ndog Cheplox</p>
            </a>
            <a
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h3>Id</h3>
              <p>260575817</p>
            </a>
            <a
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h3>Waktu Posting</h3>
              <p>2023-06-04 11:34:32</p>
            </a>
            <a
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h3>Text</h3>
              <p>
                Katanya sistem beli karcisnya: 1 KTP cuma bisa beli 2 tiket
                untuk menghindari calo... ~ iya kali calo kagak punya sodara
                atau temen.... ??? https://t.co/ukdBqjht9T
              </p>
            </a>
          </div>
        </div>
        <br />
        <br />
        <div className={styles.card} target="_blank" rel="noopener noreferrer">
          <div
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h3>User yang paling berdampak</h3>
          </div>
        </div>
        <div className={styles.grud}>
          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h3>Username</h3>
            <p>mwv.mystic</p>
          </a>
          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h3>Id</h3>
            <p>1179451804280479744</p>
          </a>
          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h3>Jumlah Posting</h3>
            <p>1</p>
          </a>
          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h3>Jumlah Retweet</h3>
            <p>509</p>
          </a>
          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h3>Jumlah Replay</h3>
            <p>113</p>
          </a>
        </div>
        <div className={styles.grud} target="_blank" rel="noopener noreferrer">
          <div
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h3>Text</h3>
            <p>
              CALO PENIPU TIKET MATCH ARGENTINA VS INDONESIA. Aku rugi puluhan
              juta dan ada banyak korban lainnya. Jangan percaya sama akun
              [input nama akun] , dia pake rekening [input nama bank] a.n [input
              nama orang] Semoga gaada lagi yang ketipu sama [input nama akun] a
              thread
            </p>
          </div>
        </div>

        <div className={styles.grud}>
          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h3>Username</h3>
            <p>Firzie A. Idris</p>
          </a>
          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h3>Id</h3>
            <p>28201831</p>
          </a>
          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h3>Jumlah Posting</h3>
            <p>1</p>
          </a>
          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h3>Jumlah Retweet</h3>
            <p>45</p>
          </a>
          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h3>Jumlah Replay</h3>
            <p>8</p>
          </a>
        </div>
        <div className={styles.card} target="_blank" rel="noopener noreferrer">
          <h3>Text</h3>
          <p>
            Dengan harga tiket premium menghadapi juara dunia, kita seharusnya
            expect pengorganisasian kelas satu dr PSSI, Tiketcom, & pengurus
            GBK. Stewarding hrs profesional, pihak pengamanan ga lagi memasukkan
            orang tanpa tiket, calo diberantas. Ini yg masih terjadi di Piala
            AFF terakhir.
          </p>
        </div>

        <div className={styles.grud}>
          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h3>Username</h3>
            <p>KimTzuyu1406</p>
          </a>
          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h3>Id</h3>
            <p>1174287141909590017</p>
          </a>
          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h3>Jumlah Posting</h3>
            <p>1</p>
          </a>
          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h3>Jumlah Retweet</h3>
            <p>31</p>
          </a>
          <a className={styles.card} target="_blank" rel="noopener noreferrer">
            <h3>Jumlah Replay</h3>
            <p>4</p>
          </a>
        </div>
        <div className={styles.card} target="_blank" rel="noopener noreferrer">
          <h3>Text</h3>
          <p>
            Tak mau calo tiket merajalela, Ketua Umum PSSI Erick Thohir
            menyampaikan bahwa di laga Indonesia vs Argentina, pihaknya akan
            berusaha memperketat penjualan tiket. Cc. @erickthohir
          </p>
        </div>

        <div className={styles.card}>
          <Image
            className={styles.logoContainer}
            src="/Calo Tiket.png"
            alt="Next.js Logo"
            width={400}
            height={250}
            priority
            float="right"
          />
        </div>
      </main>
    </>
  );
}
