import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [searchTerm, setSearchTerm] = useState("");
  const [filteredTopics, setFilteredTopics] = useState([]);

  const topics = [
    {
      id: "1",
      title: "BSI mobile",
      slug: "BSI_Mobile",
    },
    {
      id: "2",
      title: "Calo Tiket",
      slug: "Calo_Tiket",
    },
    {
      id: "3",
      title: "Messi",
      slug: "Messi",
    },
  ];

  const handleSearch = (event) => {
    const searchTerm = event.target.value;
    setSearchTerm(searchTerm);

    const filteredTopics = topics.filter((topic) =>
      topic.title.toLowerCase().includes(searchTerm.toLowerCase())
    );
    setFilteredTopics(filteredTopics);
  };

  const topicsToDisplay = searchTerm ? filteredTopics : topics;

  return (
    <>
      <Head>
        <title>List Analisis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <div>
            <a href="/">
              <h3>Home</h3>
            </a>
          </div>
          <p>By Muhammad Nurharianto</p>
        </div>
        <h1>Trending Topik</h1>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/Logo_3.png"
            alt="Next.js Logo"
            width={250}
            height={250}
            priority
          />
        </div>
        <h3>Pilih topik:</h3>
        {}
        <input
          type="text"
          placeholder="Cari topik..."
          value={searchTerm}
          onChange={handleSearch}
        />
        <br />
        <ul>
          {topicsToDisplay.map((topic) => (
            <div className={styles.card} key={topic.id}>
              <li>
                <a
                  href={`/posts/${topic.slug}`}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  {topic.title}
                </a>
              </li>
            </div>
          ))}
        </ul>
      </main>
    </>
  );
}
