import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Analisis Trending Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>Analisis Trending Twitter</p>
          <div>
            <a
              href="https://www.linkedin.com/in/muh-nur-746571216/"
              target="_blank"
              rel="noopener noreferrer"
            >
              By <h3>Muhammad Nurharianto</h3>
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/Logo_3.png"
            alt="Next.js Logo"
            width={250}
            height={250}
            priority
          />

          <h1> Analisis Trending Topik</h1>
        </div>

        <div className={styles.grid}>
          <a
            href="/tentang_Analisis"
            className={styles.card}
            target=""
            rel="noopener noreferrer"
          >
            <h2>
              Tentang Analisis <span>-&gt;</span>
            </h2>
            <p>
              Profil singkat tentang program analisis mulai dari Alur, Metode
              dan &nbsp;Cara kerja sistem.
            </p>
          </a>

          <a
            href="https://twitter.com/i/trends"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Trending Twitter <span>-&gt;</span>
            </h2>
            <p>
              Menuju langsung ke halaman twitter untuk melihat
              langsung&nbsp;trending twitter saat ini.
            </p>
          </a>

          <a
            Link
            href="/Analisis"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2>
              List Analisis <span>-&gt;</span>
            </h2>
            <p>
              Berisi hasil analisa trending twitter yang sudah
              dilakukan&nbsp;oleh kami sebelumnya.
            </p>
          </a>

          <a href="/Request" className={styles.card} rel="noopener noreferrer">
            <h2>
              Request <span>-&gt;</span>
            </h2>
            <p>
              Memberikan opsi kepada user untuk meminta request terhadap
              trending twitter&nbsp;yang belum dianalisa oleh kami.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
