import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import React, { useState } from "react";
import { getFirestore, collection, addDoc } from "firebase/firestore";
import { initializeApp } from "firebase/app";
import "firebase/firestore";

const inter = Inter({ subsets: ["latin"] });
// Inisialisasi Firebase
const firebaseConfig = {
  apiKey: "AIzaSyD0jTDf4ZRqtZ29dfgj5tEOJABh9-zmwpI",
  authDomain: "skripsi-9a62a.firebaseapp.com",
  projectId: "skripsi-9a62a",
  storageBucket: "skripsi-9a62a.appspot.com",
  messagingSenderId: "617411179816",
  appId: "1:617411179816:web:06aaadf928031ca7f04c1d",
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const InputForm = () => {
  const [inputValue, setInputValue] = useState("");

  const handleSubmit = async (e) => {
    e.preventDefault();

    try {
      // Menambahkan data ke koleksi "DataInput"
      await addDoc(collection(db, "DataInput"), { input: inputValue });
      setInputValue("");
      console.log("Data berhasil disimpan ke Firestore");
    } catch (error) {
      console.error("Terjadi kesalahan saat menyimpan data:", error);
    }
  };
  return (
    <>
      <Head>
        <title>List Analisis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <div>
            <a href="/">
              <h3>Home</h3>
            </a>
          </div>
          <p>By Muhammad Nurharianto</p>
        </div>
        <div className={styles.card}>
          <h1>Input Kata Kunci Request</h1>
          <form onSubmit={handleSubmit}>
            <input
              type="text"
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
            />
            <button type="submit">Submit</button>
          </form>
        </div>
      </main>
    </>
  );
};

export default InputForm;
