import { useRouter } from "next/router";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { useState, useEffect, useRef } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Post() {
  const [showNavigation, setShowNavigation] = useState(true);
  const [buttonVisible, setButtonVisible] = useState(false);
  const [isMinimized, setIsMinimized] = useState(false);
  const navigationRef = useRef(null);

  const toggleNavigation = () => {
    setShowNavigation(!showNavigation);
  };

  const toggleMinimize = () => {
    setIsMinimized(!isMinimized);
  };

  useEffect(() => {
    const handleScroll = () => {
      const navigationElement = navigationRef.current;
      if (navigationElement) {
        const rect = navigationElement.getBoundingClientRect();
        const isVisible = rect.top >= 0;
        setButtonVisible(!isVisible);
      }
    };
    // Tambahkan event listener saat komponen dipasang
    window.addEventListener("scroll", handleScroll);

    // Hapus event listener saat komponen dilepas
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Tentang Analisa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Tombol Minimize/Expand Navigation */}
      <button
        className={`${styles["minimize-button"]} ${
          showNavigation ? "" : styles["minimized"]
        }`}
        onClick={toggleMinimize}
      >
        {isMinimized ? "Expand Navigation" : "Minimize Navigation"}{" "}
        <span className={styles.arrow}>{isMinimized ? "▼" : "▲"}</span>
      </button>

      <div
        ref={navigationRef}
        className={`${styles.navigation} ${
          showNavigation ? "" : styles["minimized"]
        }`}
      >
        {showNavigation && (
          <div className={styles.navigation}>
            <a href="#User">User Pertama yang memicu trending</a>
            <a href="#User2">User yang paling berkontribusi</a>
            <a href="#User3">Persebaraan data</a>
          </div>
        )}
      </div>

      <main
        className={`${styles.main} ${inter.className} ${
          showNavigation ? "" : styles.showNavigation
        }`}
      >
        <div className={styles.description}>
          <div>
            <a href="/">
              <h3>Home</h3>
            </a>
          </div>
          <p>By Muhammad Nurharianto</p>
        </div>
        <div className={styles.card}>
          <h1>Cara Kerja</h1>
          <div id="User" className={styles.card}>
            <Image
              className={styles.logoContainer}
              src="/Alur.png"
              alt="Next.js Logo"
              width={600}
              height={400}
              priority
              float="right"
            />
          </div>
          <div id="User2" className={styles.card}>
            <h1>Filtering Data</h1> <br />
            <Image
              className={styles.logoContainer}
              src="/DIagram Grafik BSI Mobile.png"
              alt="Next.js Logo"
              width={600}
              height={400}
              priority
              float="right"
            />
          </div>
          <div id="User3" className={styles.card}>
            <h1>Analisa Data</h1> <br />
            <Image
              className={styles.logoContainer}
              src="/Hasil 4.png"
              alt="Next.js Logo"
              width={600}
              height={400}
              priority
              float="right"
            />
          </div>
          <div id="Tentang-kami" className={styles.card}>
            <h1>Tentang Kami</h1> <br />
            Analisa ini dibuat untuk menyelesaikan Tugas akhir pada jurusan
            Teknik Elektro Universitas Pendiidkan Indonesia dengan detail
            sebagai berikut <br />
            Nama : Muhammad Nurharianto <br />
            Pembimbing 1 : <br />
            Pembimbing 2 :
          </div>
        </div>
      </main>
    </>
  );
}
