import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Collapse from "./Collapse";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Tentang Analisis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <div>
            <a href="/">
              <h3>Home</h3>
            </a>
          </div>
          <p>By Muhammad Nurharianto</p>
        </div>
        <div className={styles.card}>
          <Collapse title="Alur Analisis" imageUrl="flowchart2.png" />
          <Collapse
            title="Cara Kerja"
            content={
              <div>
                Analisis ini dibuat dengan beberapa tahapan antara lain <br />
                <Collapse title="Filterisasi data" className="sub-collapse" />
                <Collapse title="Analisa data" className="sub-collapse" />
                <Collapse title="Visualisasi data" className="sub-collapse" />
              </div>
            }
          ></Collapse>
          <Collapse
            title="Tentang kami"
            content={
              <div>
                Analisa ini dibuat untuk menyelesaikan Tugas akhir pada jurusan
                Teknik Elektro Universitas Pendiidkan Indonesia dengan detail
                sebagai berikut <br />
                Nama : Muhammad Nurharianto <br />
                Pembimbing 1 : <br />
                Pembimbing 2 :
              </div>
            }
          />
        </div>
      </main>
    </>
  );
}
